### ISSUE TITLE
libturbojpeg0 not found

### ISSUE THREAD

**Issue by ashleyabraham** [VirtualGL/vglcygsetup#1]
When I run the script I get the following in Cygwin setup script vglcygsetup

Problem 1/1
nothing provides libturbojpeg0 needed by VirtualGL-2.6.3-20191024
Solution 1/1 (default)
  - allow replacement of VirtualGL-2.6.3-20191024 with VirtualGL-2.4.90-20151027

I couldn't find where to find libturbojpeg0

**Comment by dcommander** [comment]
vglcygsetup is admittedly a hack.  The ultimate solution is for someone to develop an official Cygwin VirtualGL Client package and submit it to the Cygwin repository, but I don't personally have the cycles to do that right now (the VirtualGL Client isn't our focus these days, since most commercial VirtualGL deployments use TurboVNC.)  In the meantime, you will need to run Cygwin Setup the "normal" way to install the TurboJPEG API library:

- Select "Install from Internet".
- When the package list screen pops up, select "View: Full" and enter "turbojpeg" into the Search field.
- Install version 1.5.3 for the "libturbojpeg0" package.

vglcygsetup should now work correctly.
